services:
  - type: web
    name: krypton-bot
    env: python
    region: frankfurt
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn dash pandas-ta python-binance
    startCommand: |
      /opt/render/project/src/.venv/bin/gunicorn --bind 0.0.0.0:$PORT wsgi:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
      - key: GUNICORN_CMD_ARGS
        value: "--workers 1 --timeout 120 --log-level debug"
    healthCheckPath: /
    autoDeploy: true