services:
  - type: web
    name: krypton-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn "wsgi:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
    healthCheckPath: /
    autoDeploy: true