services:
  - type: web
    name: krypton-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level debug wsgi:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: GUNICORN_CMD_ARGS
        value: "--preload"
    healthCheckPath: /
    autoDeploy: true