services:
  - type: web
    name: krypton-bot
    env: python
    region: frankfurt
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn dash pandas-ta python-binance flask
    startCommand: |
      source /opt/render/project/src/.venv/bin/activate && \
      gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level debug app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
    healthCheckPath: /
    autoDeploy: true