services:
  - type: web
    name: krypton-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn --bind 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 120 --workers 1"
    healthCheckPath: /
    autoDeploy: true