services:
  - type: web
    name: krypton-bot
    env: python
    region: frankfurt
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install dash gunicorn pandas-ta python-binance
    startCommand: |
      python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
      - key: DASH_DEBUG
        value: "false"
    healthCheckPath: /
    autoDeploy: true